name: Ansible Run Playbook

on:
  release:
    types: [published]
  push:
    branches:
      - staging
      - main

jobs:
  Ansible:
    name: Ansible
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

#    - name: Wait for tests to succeed
#      uses: lewagon/wait-on-check-action@master
#      with:
#        ref: ${{ github.sha }}
#        running-workflow-name: 'Ansible'
#        repo-token: ${{ secrets.GITHUB_TOKEN }}
#        wait-interval: 10
#        check-regexp: .?-lint

    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        # Required, playbook filepath
        playbook: site.yml
        # Optional, directory where playbooks live
        directory: ./lamp_simple
        # Optional, SSH private key
        key: ${{secrets.SSH_PRIVATE_KEY}}
